### ISSUE TITLE
Add profile picture links of soc cordis to json file.

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/Saarani-frontend#49]
In the `backend` folder there's a `society.json` file, you have to add links of profile pics (hosted on imgur or whatever image hosting site) and add it to the file in the following manner:
```
{
  "geekhaven": {
    "coordinators": ["Manthan Raju Surkar", "Prateek Mishra"],
    "email": "geekhaven@iiita.ac.in",
    "name": "Geekhaven",
    "desc": "Technical Society",
    "insta": "geekhaven_iiita",
    "fb": "https://www.facebook.com/geekhaveniiita/"
  }
```

add the url inside the json array making a json object like 

```
{
  "geekhaven": {
    "coordinators": [{"Manthan Raju Surkar" : "https://image_url" }, { "Prateek Mishra" : "https://image_url"}],
    "email": "geekhaven@iiita.ac.in",
    "name": "Geekhaven",
    "desc": "Technical Society",
    "insta": "geekhaven_iiita",
    "fb": "https://www.facebook.com/geekhaveniiita/"
  },
```

**Comment by geeks5551** [comment]
can i work on this issue @starboi02

**Comment by starboi02** [comment]
@geeks5551 sure go ahead and feel free to ask if you get stuck anywhere.

**Comment by Codedude1** [comment]
I would like to work on this

**Comment by starboi02** [comment]
@Codedude1 go ahead

**Comment by DevilAJ** [comment]
Can I also work on it.

**Comment by starboi02** [comment]
@DevilAJ sure you can , so lets divide the work @Codedude1 you do the first 7 socs and @DevilAJ you do the rest 8 socs.

**Comment by starboi02** [comment]
@DevilAJ @Codedude1 is this okay with both of you?

**Comment by DevilAJ** [comment]
@starboi02 fine by me..

**Comment by Codedude1** [comment]
Actually, I've done all the 15 socs. I did not notice @DevilAJ's comment.

**Comment by Codedude1** [comment]
Shall I create a PR then?

**Comment by starboi02** [comment]
@Codedude1 no problem @DevilAJ sorry but you can claim other unclaimed issues :(

**Comment by starboi02** [comment]
@Codedude1 yeah make the PR

**Comment by DevilAJ** [comment]
Ok

**Comment by Codedude1** [comment]
Also, I could not find images of two coordinators(Divyansh Bhorvanshi and Parag Goyal sir).  @starboi02

**Comment by starboi02** [comment]
@Codedude1 no problem, thanks for your contribution :)
