### ISSUE TITLE
Replace card view with circular image view

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/Saarani-frontend#50]
In `soc_profile_cordi.xml` and `soc_profile_cordi_alt.xml` replace card view with `hdodenhof circular image view` (dependency already added). You can refer to `about_us.xml` to get some insight about what exactly we need to implement.

**Comment by Devildarkfire** [comment]
I want to work on it

**Comment by snehal2841** [comment]
Will you assign it to me? I want to work on it.

**Comment by starboi02** [comment]
@Devildarkfire go ahead

**Comment by starboi02** [comment]
@snehal2841 if @Devildarkfire fails to make a PR in 2 days it will be assigned to you thereafter.

**Comment by starboi02** [comment]
@Devildarkfire provide your SHA key for setting up the firebase.

**Comment by Devildarkfire** [comment]
#ssh key
SHA256:3EWb8ePGrfJNp3NVZQHbKoBctw3LVOPprtg1KBYJ5Wo

**Comment by VarunT11** [comment]
@Devildarkfire Please provide a correct SHA-1 Key. The Key provided by you is invalid.

**Comment by Devildarkfire** [comment]
SHA1: 7F:99:04:A0:4D:A3:2A:0C:F5:6D:0D:15:5C:66:C8:09:3C:0B:2F:24

**Comment by VarunT11** [comment]
@Devildarkfire I have added your SHA-1 Fingerprint, you may proceed with your work.
