### ISSUE TITLE
Add SwipeRefreshLayout as the root layout of `main_fragment.xml` and `list_fragment.xml`

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/Saarani-frontend#53]
For ref you can refer to https://medium.com/@houdayer.corentin/how-to-use-swipe-to-refresh-swiperefreshlayout-99abd674c907 .

**Comment by Pranshu-Tripathi** [comment]
can I work on this ?

**Comment by starboi02** [comment]
Sure go ahead!
Please provide your SHA key also.

**Comment by Pranshu-Tripathi** [comment]
SHA key ... Please Add and notify me 
SHA1: 45:29:8C:8B:1F:13:B6:9C:E7:53:85:BA:2B:8F:7B:9A:5B:68:35:8B

**Comment by starboi02** [comment]
@Pranshu-Tripathi you can start working now, have added your SHA key.

**Comment by Pranshu-Tripathi** [comment]
@starboi02  I am facing some issue while setting up this project as seen from screen shot inspite of the version of gradle being 4.1.0 Please suggest changes i need to do.

Here is the screenshot.

![Screenshot (44)](https://user-images.githubusercontent.com/58396213/96256818-f43d2d00-0fd6-11eb-9d26-58331e615b5c.png)

**Comment by starboi02** [comment]
@Pranshu-Tripathi sorry for the late response was busy with some engagements :( So is the problem solved now?

**Comment by Pranshu-Tripathi** [comment]
@starboi02 , thanks for responding , I have resolved that problem by downgrading my gradle to 3.6.4.  I have sent a PR also please review it and mention any aments are needed or not :).
