### ISSUE TITLE
Implement functionality of swipeRefreshLayout in MainFragment

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/Saarani-frontend#57]
In main fragment on swiped data should be fetched from server `( loadRecyclerViewData() function )` and current selected date should be changed by current date.

**Comment by siddhantdrk** [comment]
can I work on this??

**Comment by starboi02** [comment]
@siddhantdrk go ahead!

**Comment by starboi02** [comment]
@siddhantdrk please provide your SHA key

**Comment by siddhantdrk** [comment]
@starboi02  here is the SHA key
SHA1: 89:52:D5:82:A5:30:EB:15:C7:FA:5E:09:FB:4E:99:ED:29:56:31:4E

**Comment by starboi02** [comment]
@siddhantdrk have added it to the firebase, you can start working on it now.
