### ISSUE TITLE
.idea file is not necessary for project

### ISSUE THREAD

**Issue by ABHAY0O7** [GeekHaven/Saarani-frontend#78]
Ig there is no use of .idea file in any project on Github, this file is useful only in personal IntelliJ IDE, and it is created automatically by Intellij. Also, not every user uses the Intellij idea, some users use other IDEs too, so this file is unuseful for them.
Also, when someone opens this project in his own Intellij then the files got overwrite automatically by IntelliJ (according to his personal idea settings) which creates a lot of mess in managing `git diff`.

So better include this file in gitIgnore so that new contributors do not get stuck in managing `.idea` file.
PS: It will decrease project size too.

**Comment by ABHAY0O7** [comment]
@VarunT11 should I move `.idea` to gitignore?

**Comment by VarunT11** [comment]
@ABHAY0O7 Yeah Sure, Go Ahead!

**Comment by ABHAY0O7** [comment]
@VarunT11 @starboi02 
I resolved this issue in #79, please check it out.
